export const CASE_STATUS = {
  DRAFT: "draft",
  CONTACT_PENDING: "contact_pending",
  SUBMITTED: "submitted",
  PROCESSING: "processing",
  REPORT_READY: "report_ready",
  REPORT_VIEWED: "report_viewed",
  CONSULT_INTENT_SUBMITTED: "consult_intent_submitted",
  ADMIN_FOLLOWING: "admin_following",
  AWAITING_USER_INFO: "awaiting_user_info",
  CONSULT_READY_FOR_ASSIGNMENT: "consult_ready_for_assignment",
  CONSULT_ASSIGNED: "consult_assigned",
  FOLLOW_UP: "follow_up",
  NURTURING: "nurturing",
  CLOSED: "closed"
} as const;

export type CaseStatus = (typeof CASE_STATUS)[keyof typeof CASE_STATUS];

export const CASE_STATUS_SEQUENCE: readonly CaseStatus[] = [
  CASE_STATUS.DRAFT,
  CASE_STATUS.CONTACT_PENDING,
  CASE_STATUS.SUBMITTED,
  CASE_STATUS.PROCESSING,
  CASE_STATUS.REPORT_READY,
  CASE_STATUS.REPORT_VIEWED,
  CASE_STATUS.CONSULT_INTENT_SUBMITTED,
  CASE_STATUS.ADMIN_FOLLOWING,
  CASE_STATUS.AWAITING_USER_INFO,
  CASE_STATUS.CONSULT_READY_FOR_ASSIGNMENT,
  CASE_STATUS.CONSULT_ASSIGNED,
  CASE_STATUS.FOLLOW_UP,
  CASE_STATUS.NURTURING,
  CASE_STATUS.CLOSED
] as const;

export const VALID_CASE_TRANSITIONS: Readonly<Record<CaseStatus, readonly CaseStatus[]>> = {
  [CASE_STATUS.DRAFT]: [CASE_STATUS.SUBMITTED, CASE_STATUS.CONTACT_PENDING],
  [CASE_STATUS.CONTACT_PENDING]: [CASE_STATUS.SUBMITTED],
  [CASE_STATUS.SUBMITTED]: [CASE_STATUS.PROCESSING],
  [CASE_STATUS.PROCESSING]: [CASE_STATUS.REPORT_READY],
  [CASE_STATUS.REPORT_READY]: [CASE_STATUS.REPORT_VIEWED],
  [CASE_STATUS.REPORT_VIEWED]: [CASE_STATUS.CONSULT_INTENT_SUBMITTED],
  [CASE_STATUS.CONSULT_INTENT_SUBMITTED]: [CASE_STATUS.ADMIN_FOLLOWING],
  [CASE_STATUS.ADMIN_FOLLOWING]: [
    CASE_STATUS.AWAITING_USER_INFO,
    CASE_STATUS.CONSULT_READY_FOR_ASSIGNMENT,
    CASE_STATUS.NURTURING
  ],
  [CASE_STATUS.AWAITING_USER_INFO]: [CASE_STATUS.ADMIN_FOLLOWING, CASE_STATUS.NURTURING],
  [CASE_STATUS.CONSULT_READY_FOR_ASSIGNMENT]: [CASE_STATUS.CONSULT_ASSIGNED],
  [CASE_STATUS.CONSULT_ASSIGNED]: [CASE_STATUS.FOLLOW_UP],
  [CASE_STATUS.FOLLOW_UP]: [CASE_STATUS.CLOSED, CASE_STATUS.NURTURING],
  [CASE_STATUS.NURTURING]: [CASE_STATUS.ADMIN_FOLLOWING],
  [CASE_STATUS.CLOSED]: [CASE_STATUS.ADMIN_FOLLOWING]
} as const;

export const STATUS_ENTRY_REQUIREMENTS: Readonly<Record<CaseStatus, readonly string[]>> = {
  [CASE_STATUS.DRAFT]: [],
  [CASE_STATUS.CONTACT_PENDING]: [],
  [CASE_STATUS.SUBMITTED]: [],
  [CASE_STATUS.PROCESSING]: [],
  [CASE_STATUS.REPORT_READY]: [],
  [CASE_STATUS.REPORT_VIEWED]: [],
  [CASE_STATUS.CONSULT_INTENT_SUBMITTED]: [],
  [CASE_STATUS.ADMIN_FOLLOWING]: [],
  [CASE_STATUS.AWAITING_USER_INFO]: [],
  [CASE_STATUS.CONSULT_READY_FOR_ASSIGNMENT]: [],
  [CASE_STATUS.CONSULT_ASSIGNED]: ["assigned_consultant_id"],
  [CASE_STATUS.FOLLOW_UP]: ["case_follow_ups >= 1"],
  [CASE_STATUS.NURTURING]: ["nurturing_reason"],
  [CASE_STATUS.CLOSED]: ["close_reason"]
} as const;

export const STATUS_TRANSITION_REQUIREMENTS: Readonly<Record<string, readonly string[]>> = {
  [`${CASE_STATUS.CLOSED}->${CASE_STATUS.ADMIN_FOLLOWING}`]: ["reopen_reason"]
} as const;

export function canTransitionCaseStatus(from: CaseStatus, to: CaseStatus): boolean {
  return VALID_CASE_TRANSITIONS[from].includes(to);
}
